### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gep13** [cake-build/bitrise-cake-step#4]
@stefandevo I have just made a slight change to use https URL's, rather than http ones.

Can you please let me know what I need to do in order to push out a new version of this?  Thanks in advance!

**Comment by gep13** [comment]
@stefandevo I also pushed a couple changes in the other bitrise repo in this org.  Is there anything I need to do here to push those changes somewhere?  Thanks!

**Comment by stefandevo** [comment]
Hi @gep13 I will have a look at it during the weekend - but for the steplib repo here, you don't need to change anything in there. The flow is that you need to clone that repo from bitrise and then do some commands via the bitrise cli that updates the cloned repo. From there a PR will be generated. But will have a look and try to put the commands in the readme!

**Comment by gep13** [comment]
@stefandevo that would be great, thank you!  Appreciate your help with this!
