### ISSUE TITLE
And document about how to use this in Bitrise

### ISSUE THREAD

**Issue by jessejiang0214** [cake-build/bitrise-cake-step#5]
Hi there, 
I try to add Cake Script workflow into Bitrise, but it doesn't work.

I added example repo https://github.com/cake-build/example
Add Cake Script after Nuget Restore like this
![screen shot 2017-10-24 at 11 07 35 am](https://user-images.githubusercontent.com/4516628/31919095-f8d565ec-b8ab-11e7-882c-2b86f27eed27.png)

And then I get Error 
![screen shot 2017-10-24 at 11 08 16 am](https://user-images.githubusercontent.com/4516628/31919113-07a93c6a-b8ac-11e7-95d9-462a498b7ee9.png)

**Comment by randalvance** [comment]
Got the same error.

**Comment by stefandevo** [comment]
There is an update available. Sorry for this delay
